(when (display-graphic-p)
  (load-file (expand-file-name "snippets/fonts-setup.el" user-emacs-directory)))
(load-file (expand-file-name "snippets/elpy-setup.el" user-emacs-directory))
(load-file (expand-file-name "snippets/web-setup.el" user-emacs-directory))
(load-file (expand-file-name "snippets/latex-setup.el" user-emacs-directory))
(load-file (expand-file-name "snippets/pyim-setup.el" user-emacs-directory))
