(load-file (expand-file-name "snippets/nano-theme-setup.el" user-emacs-directory))
(load-file (expand-file-name "snippets/elpy-setup.el" user-emacs-directory))
(load-file (expand-file-name "snippets/web-setup.el" user-emacs-directory))
(load-file (expand-file-name "snippets/latex-setup.el" user-emacs-directory))
(load-file (expand-file-name "snippets/pyim-setup.el" user-emacs-directory))
