(load-file (expand-file-name "misc/fonts-setup.el" user-emacs-directory))
(load-file (expand-file-name "misc/semantic-setup.el" user-emacs-directory))
(load-file (expand-file-name "misc/eglot-setup.el" user-emacs-directory))
(load-file (expand-file-name "misc/python-setup.el" user-emacs-directory))
(load-file (expand-file-name "misc/web-setup.el" user-emacs-directory))
(load-file (expand-file-name "misc/latex-setup.el" user-emacs-directory))
(load-file (expand-file-name "misc/pyim-setup.el" user-emacs-directory))
